// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalShellExecAction } from "./LocalShellExecAction";

export type LocalShellAction = { "type": "exec" } & LocalShellExecAction;
