// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParsedCommand = { "type": "read", cmd: string, name: string,
/**
 * (Best effort) Path to the file being read by the command. When
 * possible, this is an absolute path, though when relative, it should
 * be resolved against the `cwd`` that will be used to run the command
 * to derive the absolute path.
 */
path: string, } | { "type": "list_files", cmd: string, path: string | null, } | { "type": "search", cmd: string, query: string | null, path: string | null, } | { "type": "unknown", cmd: string, };
