// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Contents returned when reading a resource from an MCP server.
 */
export type ResourceContent = {
/**
 * The URI of this resource.
 */
uri: string, mimeType?: string, text: string, _meta?: JsonValue, } | {
/**
 * The URI of this resource.
 */
uri: string, mimeType?: string, blob: string, _meta?: JsonValue, };
