// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls output length/detail on GPT-5 models via the Responses API.
 * Serialized with lowercase values to match the OpenAI API.
 */
export type Verbosity = "low" | "medium" | "high";
