/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigFileResponse {
    #[serde(rename = "contents", skip_serializing_if = "Option::is_none")]
    pub contents: Option<String>,
    #[serde(rename = "sha256", skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "updated_by_user_id", skip_serializing_if = "Option::is_none")]
    pub updated_by_user_id: Option<String>,
}

impl ConfigFileResponse {
    pub fn new(
        contents: Option<String>,
        sha256: Option<String>,
        updated_at: Option<String>,
        updated_by_user_id: Option<String>,
    ) -> ConfigFileResponse {
        ConfigFileResponse {
            contents,
            sha256,
            updated_at,
            updated_by_user_id,
        }
    }
}
