/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedListTaskListItem {
    #[serde(rename = "items")]
    pub items: Vec<models::TaskListItem>,
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl PaginatedListTaskListItem {
    pub fn new(items: Vec<models::TaskListItem>) -> PaginatedListTaskListItem {
        PaginatedListTaskListItem {
            items,
            cursor: None,
        }
    }
}
