// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanType } from "../PlanType";

export type Account = { "type": "apiKey", } | { "type": "chatgpt", email: string, planType: PlanType, };
