// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppBranding } from "./AppBranding";
import type { AppMetadata } from "./AppMetadata";

/**
 * EXPERIMENTAL - app metadata returned by app-list APIs.
 */
export type AppInfo = { id: string, name: string, description: string | null, logoUrl: string | null, logoUrlDark: string | null, distributionChannel: string | null, branding: AppBranding | null, appMetadata: AppMetadata | null, labels: { [key in string]?: string } | null, installUrl: string | null, isAccessible: boolean,
/**
 * Whether this app is enabled in config.toml.
 * Example:
 * ```toml
 * [apps.bad_app]
 * enabled = false
 * ```
 */
isEnabled: boolean, pluginDisplayNames: Array<string>, };
