// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppInfo } from "./AppInfo";

/**
 * EXPERIMENTAL - notification emitted when the app list changes.
 */
export type AppListUpdatedNotification = { data: Array<AppInfo>, };
