// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [UNSTABLE] Source that produced a terminal approval auto-review decision.
 */
export type AutoReviewDecisionSource = "agent";
