// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Write stdin bytes to a running `command/exec` session, close stdin, or
 * both.
 */
export type CommandExecWriteParams = {
/**
 * Client-supplied, connection-scoped `processId` from the original
 * `command/exec` request.
 */
processId: string,
/**
 * Optional base64-encoded stdin bytes to write.
 */
deltaBase64?: string | null,
/**
 * Close stdin after writing `deltaBase64`, if present.
 */
closeStdin?: boolean, };
