// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final buffered result for `command/exec`.
 */
export type CommandExecResponse = {
/**
 * Process exit code.
 */
exitCode: number,
/**
 * Buffered stdout capture.
 *
 * Empty when stdout was streamed via `command/exec/outputDelta`.
 */
stdout: string,
/**
 * Buffered stderr capture.
 *
 * Empty when stderr was streamed via `command/exec/outputDelta`.
 */
stderr: string, };
