// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Empty success response for `command/exec/terminate`.
 */
export type CommandExecTerminateResponse = Record<string, never>;
