// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminate a running `command/exec` session.
 */
export type CommandExecTerminateParams = {
/**
 * Client-supplied, connection-scoped `processId` from the original
 * `command/exec` request.
 */
processId: string, };
