// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigRequirements } from "./ConfigRequirements";

export type ConfigRequirementsReadResponse = {
/**
 * Null if no requirements are configured (e.g. no requirements.toml/MDM entries).
 */
requirements: ConfigRequirements | null, };
