// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextRange } from "./TextRange";

export type ConfigWarningNotification = {
/**
 * Concise summary of the warning.
 */
summary: string,
/**
 * Optional extra guidance or error details.
 */
details: string | null,
/**
 * Optional path to the config file that triggered the warning.
 */
path?: string,
/**
 * Optional range for the error location inside the config file.
 */
range?: TextRange, };
