// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExperimentalFeatureEnablementSetParams = {
/**
 * Process-wide runtime feature enablement keyed by canonical feature name.
 *
 * Only named features are updated. Omitted features are left unchanged.
 * Send an empty map for a no-op.
 */
enablement: { [key in string]?: boolean }, };
