// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalAgentConfigDetectParams = {
/**
 * If true, include detection under the user's home (~/.claude, ~/.codex, etc.).
 */
includeHome?: boolean,
/**
 * Zero or more working directories to include for repo-scoped detection.
 */
cwds?: Array<string> | null, };
