// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Copy a file or directory tree on the host filesystem.
 */
export type FsCopyParams = {
/**
 * Absolute source path.
 */
sourcePath: AbsolutePathBuf,
/**
 * Absolute destination path.
 */
destinationPath: AbsolutePathBuf,
/**
 * Required for directory copies; ignored for file copies.
 */
recursive?: boolean, };
