// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Request metadata for an absolute path.
 */
export type FsGetMetadataParams = {
/**
 * Absolute path to inspect.
 */
path: AbsolutePathBuf, };
