// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata returned by `fs/getMetadata`.
 */
export type FsGetMetadataResponse = {
/**
 * Whether the path resolves to a directory.
 */
isDirectory: boolean,
/**
 * Whether the path resolves to a regular file.
 */
isFile: boolean,
/**
 * Whether the path itself is a symbolic link.
 */
isSymlink: boolean,
/**
 * File creation time in Unix milliseconds when available, otherwise `0`.
 */
createdAtMs: number,
/**
 * File modification time in Unix milliseconds when available, otherwise `0`.
 */
modifiedAtMs: number, };
