// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Remove a file or directory tree from the host filesystem.
 */
export type FsRemoveParams = {
/**
 * Absolute path to remove.
 */
path: AbsolutePathBuf,
/**
 * Whether directory removal should recurse. Defaults to `true`.
 */
recursive?: boolean | null,
/**
 * Whether missing paths should be ignored. Defaults to `true`.
 */
force?: boolean | null, };
