// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Read a file from the host filesystem.
 */
export type FsReadFileParams = {
/**
 * Absolute path to read.
 */
path: AbsolutePathBuf, };
