// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Base64-encoded file contents returned by `fs/readFile`.
 */
export type FsReadFileResponse = {
/**
 * File contents encoded as base64.
 */
dataBase64: string, };
