// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A directory entry returned by `fs/readDirectory`.
 */
export type FsReadDirectoryEntry = {
/**
 * Direct child entry name only, not an absolute or relative path.
 */
fileName: string,
/**
 * Whether this entry resolves to a directory.
 */
isDirectory: boolean,
/**
 * Whether this entry resolves to a regular file.
 */
isFile: boolean, };
