// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stop filesystem watch notifications for a prior `fs/watch`.
 */
export type FsUnwatchParams = {
/**
 * Watch identifier previously provided to `fs/watch`.
 */
watchId: string, };
