// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Start filesystem watch notifications for an absolute path.
 */
export type FsWatchParams = {
/**
 * Connection-scoped watch identifier used for `fs/unwatch` and `fs/changed`.
 */
watchId: string,
/**
 * Absolute file or directory path to watch.
 */
path: AbsolutePathBuf, };
