// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Successful response for `fs/watch`.
 */
export type FsWatchResponse = {
/**
 * Canonicalized path associated with the watch.
 */
path: AbsolutePathBuf, };
