// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Write a file on the host filesystem.
 */
export type FsWriteFileParams = {
/**
 * Absolute path to write.
 */
path: AbsolutePathBuf,
/**
 * File contents encoded as base64.
 */
dataBase64: string, };
