// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type GetAccountRateLimitsResponse = {
/**
 * Backward-compatible single-bucket view; mirrors the historical payload.
 */
rateLimits: RateLimitSnapshot,
/**
 * Multi-bucket view keyed by metered `limit_id` (for example, `codex`).
 */
rateLimitsByLimitId: { [key in string]?: RateLimitSnapshot } | null, };
