// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [UNSTABLE] Authorization level assigned by approval auto-review.
 */
export type GuardianUserAuthorization = "unknown" | "low" | "medium" | "high";
