// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { McpServerElicitationAction } from "./McpServerElicitationAction";

export type McpServerElicitationRequestResponse = { action: McpServerElicitationAction,
/**
 * Structured user input for accepted elicitations, mirroring RMCP `CreateElicitationResult`.
 *
 * This is nullable because decline/cancel responses have no content.
 */
content: JsonValue | null,
/**
 * Optional client metadata for form-mode action handling.
 */
_meta: JsonValue | null, };
