// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillsListExtraRootsForCwd } from "./SkillsListExtraRootsForCwd";

export type SkillsListParams = {
/**
 * When empty, defaults to the current session working directory.
 */
cwds?: Array<string>,
/**
 * When true, bypass the skills cache and re-scan skills from disk.
 */
forceReload?: boolean,
/**
 * Optional per-cwd extra roots to scan as user-scoped skills.
 */
perCwdExtraUserRoots?: Array<SkillsListExtraRootsForCwd> | null, };
