// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillToolDependency = { type: string, value: string, description?: string, transport?: string, command?: string, url?: string, };
