// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextPosition = {
/**
 * 1-based line number.
 */
line: number,
/**
 * 1-based column number (in Unicode scalar values).
 */
column: number, };
