// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDirection } from "./SortDirection";

export type ThreadTurnsListParams = { threadId: string,
/**
 * Opaque cursor to pass to the next call to continue after the last turn.
 */
cursor?: string | null,
/**
 * Optional turn page size.
 */
limit?: number | null,
/**
 * Optional turn pagination direction; defaults to descending.
 */
sortDirection?: SortDirection | null, };
