// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadMetadataGitInfoUpdateParams = {
/**
 * Omit to leave the stored commit unchanged, set to `null` to clear it,
 * or provide a non-empty string to replace it.
 */
sha?: string | null,
/**
 * Omit to leave the stored branch unchanged, set to `null` to clear it,
 * or provide a non-empty string to replace it.
 */
branch?: string | null,
/**
 * Omit to leave the stored origin URL unchanged, set to `null` to clear it,
 * or provide a non-empty string to replace it.
 */
originUrl?: string | null, };
