// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - transport used by thread realtime.
 */
export type ThreadRealtimeStartTransport = { "type": "websocket" } | { "type": "webrtc",
/**
 * SDP offer generated by a WebRTC RTCPeerConnection after configuring audio and the
 * realtime events data channel.
 */
sdp: string, };
