// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WarningNotification = {
/**
 * Optional thread target when the warning applies to a specific thread.
 */
threadId: string | null,
/**
 * Concise warning message for the user.
 */
message: string, };
